databases:
  - name: apidb
    plan: free
    databaseName: apidb
    user: apidb

services:
  - type: worker
    plan: free
    name: celery-worker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app api worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString

  - type: web
    plan: free
    name: api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn api.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apidb
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  
  - type: redis
    name: celery-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []